/**
 * 异常代码枚举
 *
 * 定义统一的异常代码，便于日志、监控和前端处理
 */
export enum ExceptionCode {
  // 领域异常
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  INVALID_STATE = "INVALID_STATE",
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  DOMAIN_INVARIANT_VIOLATION = "DOMAIN_INVARIANT_VIOLATION",

  // 应用异常
  USE_CASE_FAILED = "USE_CASE_FAILED",
  CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT",
  COMMAND_HANDLER_FAILED = "COMMAND_HANDLER_FAILED",
  QUERY_HANDLER_FAILED = "QUERY_HANDLER_FAILED",

  // 基础设施异常
  DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED",
  DB_QUERY_FAILED = "DB_QUERY_FAILED",
  EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE",
  MQ_UNAVAILABLE = "MQ_UNAVAILABLE",
  CACHE_ERROR = "CACHE_ERROR",
  FILE_SYSTEM_ERROR = "FILE_SYSTEM_ERROR",

  // 验证异常
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

  // 认证授权异常
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

  // 通用异常
  INTERNAL_ERROR = "INTERNAL_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
}
